# Generated by Django 5.0.2 on 2024-02-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MZE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumptionrecord',
            name='frequency',
            field=models.FloatField(blank=True, help_text='Frequency in Hz', null=True),
        ),
        migrations.AddField(
            model_name='energyconsumptionrecord',
            name='resistance',
            field=models.FloatField(blank=True, help_text='Resistance in Ohms', null=True),
        ),
        migrations.AddField(
            model_name='energyconsumptionrecord',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in Celsius', null=True),
        ),
        migrations.AddField(
            model_name='energyconsumptionrecord',
            name='voltage',
            field=models.FloatField(blank=True, help_text='Voltage in Volts', null=True),
        ),
    ]
