# Generated by Django 5.0.2 on 2024-02-29 11:39

import MZE.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MZE', '0002_energyconsumptionrecord_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sensors',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default=MZE.models.generate_serial_number, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TemperatureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('measurement_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_measurements', to='MZE.device')),
            ],
        ),
        migrations.CreateModel(
            name='VoltageMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('measurement_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voltage_measurements', to='MZE.device')),
            ],
        ),
        migrations.DeleteModel(
            name='EnergyConsumptionRecord',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
