# Generated by Django 5.0.3 on 2024-04-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('energy_consumption', models.FloatField()),
            ],
        ),
    ]
