# Generated by Django 5.0.3 on 2024-04-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MZE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energyconsumption',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Energy Consumption', 'verbose_name_plural': 'Energy Consumptions'},
        ),
    ]
